#!/bin/bash

# Adapted from original pipeline provided by Marta Ibañez Lligoña
# Contact: marta.ibanez@vhir.org

## Create directory to save the report files
mkdir -p "/home/sumeyye/Desktop/GBS1_26/results/fastqc"

## set path to new directory as cleanfastq
cleanfastq="/home/sumeyye/Desktop/GBS1_26/results/fastqc"

## run fastqc through all documents with just one command, you need to add the fastqs path where your files are located, *.fastq.gz is selecting all files at once.
fastqc /home/sumeyye/Desktop/GBS1_26/data/*.fastq.gz -t 8 -o $cleanfastq
